import type { Payment } from '../types/Payment';

const today = new Date();
const buildDate = (offsetDays: number): string => {
  const date = new Date(today.getFullYear(), today.getMonth(), today.getDate() + offsetDays);
  const day = String(date.getDate()).padStart(2, '0');
  const month = String(date.getMonth() + 1).padStart(2, '0');
  return `${day}/${month}/${date.getFullYear()}`;
};

export const paymentsMock: Payment[] = [
  {
    id: 'pay-rent-jan',
    description: 'Aluguel Janeiro',
    amount: 2800,
    groupId: 'rep-universitaria',
    groupName: 'República Universitária',
    commitmentId: 'rent-jan',
    commitmentName: 'Aluguel Janeiro',
    payerId: 'ana-lima',
    payerName: 'Ana Lima',
    category: 'Aluguel',
    method: 'pix',
    recurrence: 'monthly',
    date: buildDate(-12),
    status: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pay-power',
    description: 'Conta de Luz',
    amount: 450,
    groupId: 'rep-universitaria',
    groupName: 'República Universitária',
    commitmentId: 'power',
    commitmentName: 'Conta de Luz',
    payerId: 'joao-costa',
    payerName: 'João Costa',
    category: 'Contas',
    method: 'boleto',
    recurrence: 'monthly',
    date: buildDate(-4),
    status: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pay-rent-feb-1',
    description: 'Aluguel Fevereiro',
    amount: 700,
    groupId: 'rep-universitaria',
    groupName: 'República Universitária',
    commitmentId: 'rent-feb',
    commitmentName: 'Aluguel Fevereiro',
    payerId: 'ana-lima',
    payerName: 'Ana Lima',
    category: 'Aluguel',
    method: 'pix',
    recurrence: 'monthly',
    date: buildDate(-2),
    notes: 'Primeira parcela',
    status: 'partial',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pay-internet',
    description: 'Internet + TV',
    amount: 320,
    groupId: 'rep-universitaria',
    groupName: 'República Universitária',
    payerId: 'rafael-torres',
    payerName: 'Rafael Torres',
    category: 'Contas',
    method: 'card',
    cardBrand: 'credit',
    recurrence: 'monthly',
    date: buildDate(2),
    status: 'pending',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'pay-market',
    description: 'Mercado da semana',
    amount: 480,
    groupId: 'viagem-rj',
    groupName: 'Viagem RJ - Carnaval',
    payerId: 'carlos-dias',
    payerName: 'Carlos Dias',
    category: 'Mercado',
    method: 'card',
    cardBrand: 'debit',
    recurrence: 'unique',
    date: buildDate(-6),
    status: 'paid',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
